# Generated by Django 2.2.1 on 2019-06-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Partner'),
        ),
    ]
